name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  Build-and-Tests:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: running infrastructure
      run: |
        cd infrastructure
        docker-compose up -d
        sleep 2s            
    - name: Setup JDK 16
      uses: actions/setup-java@v3
      with:
        java-version: '16'
        distribution: 'adopt'
        architecture: x64
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.0
      with:
        reports: '**/jacoco.exec'
        reporttypes: 'Html;Badges'
        targetdir: 'docs' # REQUIRED # The directory where the generated report should be saved.
        historydir: 'docs/history'
        sourcedirs: 'src' 
    - name: Push Report
      uses: EndBug/add-and-commit@v4
      with:
        add: 'docs/*'
        message: "Coverage Report ${{github.sha}}"
        ref: 'gh-pages' 
        remove: ''  
      if: ${{ github.ref == 'refs/heads/main' }}
    - name: Publish Unit Test Results
      uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1
      if: ${{ github.ref == 'refs/heads/main' && always() }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: src/**/Report.xml
